### ISSUE TITLE
Add an overlay to homeport

### ISSUE THREAD

**Issue by tsuginosuperstar** [antest1/kcanotify#1]
It would be easier to track fleet info (including things like LoS and planes) if there is a static screen where you can check it on demand. The button for it could be placed where the Friends button is (currently greyed out).

**Comment by antest1** [comment]
Good idea for placing button in Friends button. I'll consider about it. 
Is there are any other essential information (like LoS, FP, etc) that can be include?

**Comment by tsuginosuperstar** [comment]
Total level (for drum expeditions), supply status, combined fleet type, support firepower. Maybe ranking points.

Another 2 uses:
1) Display individual ship information. For example, you could set a 85-90% transparent overlay in Fleet menu and just display ship data on top of each girl's box (replace Japanese ship name with translation etc). You could make each screen have its own overlay (like KCV has individual menus), and then display everything on the homeport. Though I imagine it would be a pain to implement.

This could also work with Battleview, now that I think about it. Desktop viewers have to show a lot of redundant data so that you don't look back and forth all the time. But since kcanotify occupies the same space as the game I think it would be good to make use of as much of 'native' information as possible.

2) Quest menu translations (KC3Kai has that option).

**Comment by sanga000** [comment]
Just want to add on this, is it possible to check morale for fleets 2, 3 and 4 as well for port overlay?

**Comment by antest1** [comment]
@sanga000 Morale for all fleets (#1~#4) will be added for port overlay.

**Comment by antest1** [comment]
FleetView is added as a homeport overlay. (From kcanotify 2.4)
