### ISSUE TITLE
Add "Follow System" for Default Language Option

### ISSUE THREAD

**Issue by wafer-li** [antest1/kcanotify#10]
After discussing with my college and checking many apps at the market, it would be better to add a new Language Option called "Follow System" as the **default option** of Language Setting

It is just follow the language setting as the system's language setting.

When the user change the system language setting, it will also change to use the proper res.

If there is no proper l16n res, it will use English.

**Comment by antest1** [comment]
ok, I'll consider about it, while checking the code related with locales.

**Comment by antest1** [comment]
the "Follow System Setting" option is added. Check 519d44c, 76b805d, and 0259ea9.
close the issue.
