### ISSUE TITLE
遠征の可否の間違いについて

### ISSUE THREAD

**Issue by hyomaaoi** [antest1/kcanotify#101]
マンスリー遠征の４４「航空装備輸送任務」の成功判断に誤りがあります。
空母系1となっていますが、２必要です。空母１で編成して可否判断するとグリーンになりますが、実際には失敗します。

**Comment by antest1** [comment]
報告してくれてありがとうございます！
教えていただいた情報通りに修正しました。（Kcanotifyのリソースを更新してください）
