### ISSUE TITLE
swaytwig.com 서버를 계속 사용하고 있나요?

### ISSUE THREAD

**Issue by WolfgangKurz** [antest1/kcanotify#103]
비용 문제로 위 서버가 앱 사용/유지에 필수가 아니라면 지원을 중단하려고 합니다.

코드 수정이 필요하다면 수정 후 앱이 배포될 때 까지는 계속 제공할 예정입니다.

**Comment by antest1** [comment]
안녕하세요,

현재 legacy 설정에 대응한 게임 데이터 업로드만 이루어지고 있어, 비용 문제가 있으시다면 지원을 중단하셔도 괜찮습니다.
어플리케이션에서 관련 설정 제거가 필요하여 가능하면 이번 주 내에 업데이트 진행한 이후 다시 알려드리겠습니다.

그동안 (특히 서비스 초반에) 서버를 지원해주셔서 감사했습니다!

**Comment by antest1** [comment]
@WolfgangKurz

2.10 rev9 업데이트에서 해당 서버를 목록에서 제외했습니다. (0e59847)
다시 한 번 감사합니다!
