### ISSUE TITLE
Incompatibility with Ad Blockers

### ISSUE THREAD

**Issue by NaokiSato102** [antest1/kcanotify#105]
Due to the fact that two types of VPNs cannot be used simultaneously on Android, we are unable to block ads, which waste our limited data, while using this app. It's quite inconvenient. While I understand that it may not be easy, would it be possible to address this by integrating a free-source ad blocker or something similar? When you say it's impossible to use, does that include this kind of situation? If so, please make it clear so that we can give up on this hope.

**Comment by antest1** [comment]
Unfortunately, it would be hard to integrate other software unrelated to kancolle gameplay.

If you want to play kancolle game itself with software using VPN, you can try [GotoBrowser](https://github.com/antest1/GotoBrowser/releases/tag/v2.11), which does not require VPN to use with kcanotify. (this application runs the regular browser version of kancolle)

To use GotoBrowser with kcanotify, you need to 1) set sniffer mode (Sniffermモード) of kcanotify as "PASSIVE" from the setting and 2) turn on broadcast mode (ブロードキャストモード) for GotoBrowser.

**Comment by NaokiSato102** [comment]
Conversely, by using that method, it would be possible to use other VPNs and enable their functions, correct? Thank you for your guidance.
