### ISSUE TITLE
Add a Nationality Filter to the Ship List

### ISSUE THREAD

**Issue by NaokiSato102** [antest1/kcanotify#106]
**Description:**  
I propose adding a nationality filter feature to the ship list.  
This feature would allow users to narrow down ships based on their nationality, which is especially useful for missions requiring specific nationalities (e.g., British destroyers).  

**Reasoning:**  
1. Missions and formations often require ships of specific nationalities.  
2. Currently, finding such ships manually in the list can be time-consuming.  
3. Adding a nationality filter will enhance convenience and improve the user experience.  

**Potential Challenges:**  
- Some ships (e.g., Hibiki) may have complex nationality classifications.  

**Proposal:**  
- Add a nationality attribute to ship data.  
- Implement a nationality filter feature in the UI's filter options.

**Comment by vytran0710** [comment]
> Hi, I'll consider adding this as filter list in future updates. (maybe adding condition on filter) Thanks for the suggestion.

Could I start with the implementation of this feature (based on available information on KCWiki)?
I'm currently reviewing the code and would be glad to help.

**Comment by vytran0710** [comment]
@antest1 Yes, I have started on it.

**Comment by antest1** [comment]
feature added in 2.11 rev4 (#109).
(thanks again to @vytran0710 for the contribution!)

**Comment by NaokiSato102** [comment]
Thanks!!
