### ISSUE TITLE
Due to a change in the Yokosuka Chinjufu IP address, kcnotify is no longer available

### ISSUE THREAD

**Issue by nekowasabi** [antest1/kcanotify#107]
Due to an update yesterday (3rd December), kcnotify is no longer available due to the impact of the Yokosuka Chinjufu server system update.
It is thought that the IP address has changed.

**Comment by antest1** [comment]
does the app still not working after update app to 2.11?

**Comment by nekowasabi** [comment]
I had raised an issue before I could add 2.11.
It worked with the app version update. Thank you!
