### ISSUE TITLE
Please add Air Power to the app.

### ISSUE THREAD

**Issue by Blueshell215** [antest1/kcanotify#108]
Hi,
I've been playing Kancolle since 2016 and recently found out about kcanotify, which has helped so much with playing on my phone. 
As I used to play on PC using KC3 Kai, a feature I really loved about that viewer was the air power stat where you can check the fighter power of the whole fleet while using CVs. Currently there's no such stat in kcanotify and I think that it would be neat if it was added if it is not too difficult.
Thank you and have a wonderful day.

**Comment by antest1** [comment]
Hello,
You can check the fleet's FP (Fighter Power) from the FleetView. (see below screenshot)

![example](https://github.com/user-attachments/assets/cab50c85-5672-4121-bcb8-60b78ff776b6)

**Comment by Blueshell215** [comment]
Oh wow now I feel dumb. I thought that was Fire Power haha.
Thanks for the pointer!
