### ISSUE TITLE
UI Suggestions

### ISSUE THREAD

**Issue by laplamgor** [antest1/kcanotify#110]
Although KCANotify works perfectly fine now, the UI seems a bit too "classic Android" style.

Some suggestions:
1. [Material design buttons](https://github.com/material-components/material-components-android/blob/master/docs/components/Button.md) (Rounded corners)
2. Add [window blur effect](https://source.android.com/docs/core/display/window-blurs) for the screen overlay (for Android 12+)
   - It also hugely improves color contrast and readability
4. Transition animation for opening / closing the screen overlay
5. Animation for moving the fairy / or rotating the screen

If you agree, I may start working on some of them myself.

Also, we may drop support for Android 6 and/or lower because the DMM GAMES official app recommends Android 7.0+ and Gotobrowser has no usage data from Android 6 or lower.

**Comment by antest1** [comment]
For UI, I think it's okay to working on what you suggested, as long as users don't experience any issues with the changes on lower Android versions (under 12). It would also be nice to have an option to not use animations.
There are a lot of things that need to be improved regarding the UI but I'm a little afraid to work on my old code lol

we may drop support for Android 4.x to 6 when those works are finished (with major version update).

**Comment by laplamgor** [comment]
working on #112
