### ISSUE TITLE
Notification 이 묶였을 때의 아이콘

### ISSUE THREAD

**Issue by WolfgangKurz** [antest1/kcanotify#15]
![photo_2017-05-12_22-00-43](https://cloud.githubusercontent.com/assets/20940566/25999050/a32ec788-375e-11e7-965d-b26709a47fe7.jpg)
하나의 알림 (깡들리티 동작중 알림)처럼 보이지만,

![photo_2017-05-12_22-00-40](https://cloud.githubusercontent.com/assets/20940566/25999049/a3268d98-375e-11e7-8d05-1b696300d981.jpg)
실제로는 넷 이상의 알림이 하나로 묶여서 표시되는 것.

깡들리티의 SVC가 작동중일 때에도 하나의 Notification 이 상주하고 있으므로, 원정/수리의 알림이 표시중인지 확인이 불가능함.

따라서 일정 수 이상의 알림일 때에는 아이콘을 변경하는 등의 별도 작업이 있는 것이 좋다고 생각됨.

Sony Xperia XZ / Android 7.1.1

**Comment by antest1** [comment]
해당 기능이 안드로이드 7.0 이상에서 지원하기 시작한 기능인 것 같은데, 일단은 관련된 부분을 찾아보겠습니다.

개발자가 안드로이드 7.0을 지원하는 기기를 가지고 있지 않으므로 실제 기기에서의 테스트에 어려움이 있음을 양해 바랍니다.

**Comment by antest1** [comment]
added in 8325eda and 38db5ca. close this issue.
