### ISSUE TITLE
2 / 3 / 4 함대 피로도 표시

### ISSUE THREAD

**Issue by WolfgangKurz** [antest1/kcanotify#16]
지원함대 키라작을 할 때, 출격하는 1, 1+2(연합) 함대는 그대로 둔 상태에서 지원함대 편성을 조작해서 키라작을 합니다.

Notification에 표시되는 피로도는 1, 1+2 함대만 표시되기에 신경쓰지 않으면 키라작이 힘듭니다.

이 부분을 옵션으로 전체 피로도를 표시하게 하는 것이 좋다고 생각됩니다.

**Comment by antest1** [comment]
많은 분들의 문의를 받은 상태인데, 그 동안의 경우 전체 피로도를 표시할 때에는 차지하는 공간이 다소 크기 때문에 자주 쓰이는 1함대 피로도만 표시하도록 했습니다.

전체 함대의 피로도의 경우 차후 모항 오버레이 등을 통해서 구현할 예정입니다. (장기적으로는 모항 오버레이가 구현되었을 떄 원정 시간을 제외한 Notification 부분의 정보를 이동시킬 계획입니다.)

Notification을 통한 전체 피로도를 표시해주는 옵션에 대해서는 임시적으로 구현하는 것도 고려하고 있습니다.

**Comment by antest1** [comment]
해당 옵션을 추가함 (8d960dd)
