### ISSUE TITLE
request url does not properly parsed in local vpn data retrieval

### ISSUE THREAD

**Issue by antest1** [antest1/kcanotify#18]
## Problem
Sometimes, the first line of request header is sliced at first chunk of data. (in some 3G Network)
Example: `POST /kcsapi/api_req_sortie/b` (some last characters omitted)
 
## Code
[From Line 119 in KcaVpnData.java](https://github.com/antest1/kcanotify/blob/master/app/src/main/java/com/antest1/kcanotify/KcaVpnData.java#L119) needs to be fixed. (Howto?)

**Comment by WolfgangKurz** [comment]
같은 세션으로 처리가 가능하다면, HTTP 첫 줄 데이터 양식을 확인하여 정상적이지 않으면 세션이 끊어지거나 정상적인 데이터가 받아질 때 까지 버퍼에 보관하는 것을 고려해 보는 것이 어떨지.

POST /kcsapi/api_port/port HTTP/1.1
**[METHOD]** **[PATH]** HTTP/**[VER]**

**Comment by antest1** [comment]
안그래도 버퍼에 보관하는 방법 쪽을 고려하고 있음. 세션은 포트 번호로 구분할 수 있으니 가능할 것 같다.
정규식까지 쓸 필요는 없을 것 같고 HTTP/1.1 제대로 들어왔는지 검사하는 정도로 충분할 것 같다. 의견 감사.

**Comment by antest1** [comment]
fixed in 37619c4. close this issue.
