### ISSUE TITLE
Battle Information Fleet Data Error

### ISSUE THREAD

**Issue by WolfgangKurz** [antest1/kcanotify#19]
3rd fleet sortied, "Bismark drei" first ship.

----

![photo_2017-08-14_21-35-12](https://user-images.githubusercontent.com/20940566/29271857-8b4e3e68-8138-11e7-803f-f9ad70973152.jpg)
Photo 1) After click sortie button. 1st, 2nd (combined) fleet displaying.

![photo_2017-08-14_21-35-06](https://user-images.githubusercontent.com/20940566/29271896-b57c3410-8138-11e7-8b74-f54de6d3a374.jpg)
Photo 2) In battle (1st battle), fleet ships didn't changed, only HP changed.

![photo_2017-08-14_21-35-09](https://user-images.githubusercontent.com/20940566/29271904-c1503688-8138-11e7-9f27-f1e712367f72.jpg)
Photo 3) In battle result (1st battle), fleet ships didn't changed, only MVP changed.

![photo_2017-08-14_21-35-10](https://user-images.githubusercontent.com/20940566/29271907-c6134ab6-8138-11e7-8791-f7e3737133fb.jpg)
Photo 4) After 1st battle, ships changed finally.

**Comment by WolfgangKurz** [comment]
Additional)

Look "Photo 4".
2nd fleet's area still there.

**Comment by antest1** [comment]
Fixed in b444471 and 113f098. Thanks for the report.
