### ISSUE TITLE
(English) HP bar of the 6th ship in the fleet is cut off

### ISSUE THREAD

**Issue by tsuginosuperstar** [antest1/kcanotify#2]
See screenshot.
![screenshot_2017-01-27-13-25-20](https://cloud.githubusercontent.com/assets/25363512/22370923/4bb19994-e494-11e6-9fe3-4515415d7e33.png)

**Comment by antest1** [comment]
I think screen resolution is concerned with this problem. what device are you using? what is resolution of the device? My Samsung Galaxy Note 4 has 2560x1440 and cut off is not occured.

![kakaotalk_20170127_014637554](https://cloud.githubusercontent.com/assets/24682743/22374069/d7b92b02-e4e7-11e6-9db4-55453913a64c.png)

**Comment by tsuginosuperstar** [comment]
http://www.gsmarena.com/lenovo_vibe_c-8101.php

Resolution is 480 x 854 (basically 3 times smaller lol). I think the font size is not scaling well.

**Comment by antest1** [comment]
ok, then I'll add layout for lower resolution.

**Comment by antest1** [comment]
Fixed in 40df84.
Please re-open if problem reoccurs after 2.0.1 rev1.
