### ISSUE TITLE
Kcanotify does not work in Truck(トラック) and Linga(リンガ) Server (~2.4.4 rev3)

### ISSUE THREAD

**Issue by antest1** [antest1/kcanotify#26]
## Problem
After 10/18 maintenance, below servers seems to be moved. (IP address is changed?)
- トラック泊地 (Truk Anchorage)
- リンガ泊地 (Lingga Anchorage)  

Since kcanotify filters kancolle packet with IP-based rule, so kcanotify fails to retrieve data for these server.

Tweet: https://twitter.com/KanColle_STAFF/status/920501465914990592

## Solution
Since I am in the Paramushir, so I don't have any information about those server. So, I'm asking for help from the community.   

**If you know the new IP address for above server, it would be help me by comment here or mail to me.**  

I'll update the application as new information is available.

**Comment by antest1** [comment]
## How to find the IP address

If you are using KC3改, you can easily check in Network Tab.  

<img src="https://upload.cc/i/pmnLUx.png" width=550/>

For another pc browsers, you may use other packet capture tool like Fiddler.

For Android, you can use [Packet Capture](https://play.google.com/store/apps/details?id=app.greyshirts.sslcapture). In this case, you may start above application after login DMM. You can find packets about kancolle easily, since it shows the application icon.

Tips: Typical kancolle server IP starts with **125 or 203**.

**Comment by RemiDre** [comment]
Truck new server ip is 203.104.209.134

**Comment by antest1** [comment]
@RemiDre Thanks for telling me.

+ new server ip for Linga is 203.104.209.167

**Comment by antest1** [comment]
Fixed in 1050972.
Since IP address may change again in Kancolle 2.0, I'll check address with prefix match rather than exact match.

**Comment by antest1** [comment]
This problem is fixed in 2.4.4 rev4. 
Close this issue.
