### ISSUE TITLE
2.4.5 Bugs 

### ISSUE THREAD

**Issue by antest1** [antest1/kcanotify#29]
- fairy does not turn red when quest finish noti
- add flagship level condition for B1 -> resolved in 1455bfe

please add for more bugs

**Comment by fajarmf94** [comment]
It's seems in this new update i got connection error when kcnotify connected
Yeah my game always get catbomb because of this. This is not my internet issue since my internet in high speed with google fiber optic

Is this vpn in this app not like before?

**Comment by antest1** [comment]
@fajarmf94 

There was no significant change in sniffer(vpn) implementation in recent versions.
Check whether the whole internet is not working when sniffer is on.

I'm getting similar issue on this by mail and reviews regardless of app versions.
It seems that this problem occurs only in some devices, so it is difficult to analyze this problem.

Kcanotify uses the source code from [NetGuard](https://github.com/M66B/NetGuard), so you may check this application works well in your phone.

I'll make new Issue about Sniffer(VPN) Issue, so you may report there.

**Comment by antest1** [comment]
Close issue, since 2.4.6 released
