### ISSUE TITLE
Ship equipment shows when you scroll, swipe or quick tap

### ISSUE THREAD

**Issue by tsuginosuperstar** [antest1/kcanotify#3]
First of all, the feature is awesome, great job! But, right now the new popup appears any time you touch a ship name, which sometimes creates the situation like pic related (unless it's intentional). 
![screenshot_2017-02-06-21-40-55](https://cloud.githubusercontent.com/assets/25363512/22665642/c5a9784c-ecb5-11e6-894f-b5270445cccb.png)

**Comment by antest1** [comment]
ok, I'll make the equipment popup also be removed when main panel (BattleView) removed.

**Comment by antest1** [comment]
fixed in a78e205.
please re-open this issue when same problem occured.
