### ISSUE TITLE
Kcanotify DOES NOT WORK for new API

### ISSUE THREAD

**Issue by antest1** [antest1/kcanotify#33]
**After 2017/11/18 maintenance, some API format related with battle has been changed.**
I'm working on issue, so please wait for a while.

**Comment by WolfgangKurz** [comment]
참전함

**Comment by WolfgangKurz** [comment]
api_dock_id => api_deck_id

**Comment by WolfgangKurz** [comment]
api_ship_lv start index from 0 (not 1)

**Comment by antest1** [comment]
padding information is removed, so all start index for damage data is changed to 0.

**Comment by antest1** [comment]
api_f_maxhp, api_e_maxhp, api_f_nowhp, api_e_nowhp has variable length (num of ship)

**Comment by WolfgangKurz** [comment]
I guess api_maxhps_combined & api_nowhps_combined also....

**Comment by antest1** [comment]
however, api_edam and api_fdam has fixed length(7), which is used for kouku, opening_atack, etc

**Comment by WolfgangKurz** [comment]
df_list index changed;

alies -> enemy -> alies -> enemy -> ...
in order

**Comment by WolfgangKurz** [comment]
api_cl_list, api_damage also.....

**Comment by antest1** [comment]
※ order of df_list is defined in at_eflag, so it does not always in exchange order
at_eflag - 0 (alies attack enemy) / 1 (enemy attack alies)

**Comment by WolfgangKurz** [comment]
api_edam, api_fdam not fixed

![image](https://user-images.githubusercontent.com/20940566/32959961-95e6987a-cc06-11e7-9c58-eafef810c652.png)

**Comment by antest1** [comment]
It seems that this problem is resolved, since there are no more bug reports coming in.

I'll close this issue. I'll re-open this issue if there exists any other problem related with new api.
