### ISSUE TITLE
防空埋護姫 KR Translation

### ISSUE THREAD

**Issue by WolfgangKurz** [antest1/kcanotify#36]
"防空埋護姫":"방공매설희",

![image](https://user-images.githubusercontent.com/20940566/33304715-c68c1c44-d44d-11e7-9dab-52e2e2f8a619.png)

방공매 _**호**_ 희

**Comment by antest1** [comment]
a4d117c

**Comment by antest1** [comment]
Fixed in a4d117c

Thanks for the report.
