### ISSUE TITLE
Suppress taiha for escort fleet flagship

### ISSUE THREAD

**Issue by NoxArt** [antest1/kcanotify#37]
Hi, because flagship if escort fleet cannot be sunk it would be neat if Kcn didn't report it as an issue (or maybe just with toast ... at least optionally). Thank you for consideration!

**Comment by antest1** [comment]
Ok, I'll consider about it. 

Since I am busy nowadays, I think it cannot be reflected before this event... orz

**Comment by antest1** [comment]
Fixed in 3451477.
Close this issue.
