### ISSUE TITLE
Add "unused" fairy?

### ISSUE THREAD

**Issue by redpizza** [antest1/kcanotify#43]
How about add "unused" fairy?
These guys unused in game, but included in Kancolle game .swf file until around 2014.
They are recycled and appear in Kancolle Kai (Playstation Vita).
![1 5 1 432](https://user-images.githubusercontent.com/31765780/35470791-5546db80-0393-11e8-8219-37bbc65fc1ec.png)![1 5 1 430](https://user-images.githubusercontent.com/31765780/35470790-551ed6e4-0393-11e8-92c7-b1b350f860fa.png)
![1 5 1 433](https://user-images.githubusercontent.com/31765780/35470792-556d6aac-0393-11e8-910d-75385f4e8ebc.png)![1 5 1 434](https://user-images.githubusercontent.com/31765780/35470793-5594c890-0393-11e8-9999-66739f17015e.png)

**Comment by antest1** [comment]
I'll take it when adding fairies.
Thanks for the resources.

**Comment by antest1** [comment]
Added in 2.5.1
Close this issue.
