### ISSUE TITLE
Expedition Check for A3 Missing Fleet Level

### ISSUE THREAD

**Issue by mindwarp42** [antest1/kcanotify#44]
The expedition condition checker isn't checking the total fleet levels in regards to expedition A3.  I got tripped up myself since I was rushing to send off an underleveled fleet to it before clocking in to work and only remembered about the ASW requirement and the flagship level requirement, so I was using the expedition condition checker to see if my fleet was good or not.  The checker said it was good, so I sent my fleet off.  The expedition came back when I went to lunch, and had failed, so I pulled up the requirements on Wikia ([http://kancolle.wikia.com/wiki/Expedition/Reference_tables#Requirements](see here)), and realized I was underleveled - the total fleet has to have 185+ in levels.  Can the total fleet level check be added in?  Thanks.

**Comment by antest1** [comment]
I'll update it in the next update.
Thanks for the report.

**Comment by antest1** [comment]
fixed in 55ab25c.
I'll close this issue after new release is uploaded.
