### ISSUE TITLE
Checking overlay permission failed on Android O

### ISSUE THREAD

**Issue by xiaozhikang0916** [antest1/kcanotify#47]
After granted permission of screen overlay in setting page, permission check failed on my Android O devices ( both real and virtual one ), and i noticed that `Settings.canDrawOverlays(getActivity())` in `SettingActivity.java:403` return a `false`, even if the permission is actually granted and work well.

I found that delay the check will work:
```java
new Handler().postDelayed(() -> {
    if (Settings.canDrawOverlays(getActivity())) {
        Toast.makeText(getActivity(), getStringWithLocale(R.string.sa_overlay_ok), Toast.LENGTH_SHORT).show();
    } else {
        Toast.makeText(getActivity(), getStringWithLocale(R.string.sa_overlay_no), Toast.LENGTH_SHORT).show();
    }
}, 3000);
```
but i think you need a more elegant way to do so.

**Comment by antest1** [comment]
Seems that related with this: https://stackoverflow.com/questions/46173460/why-in-android-o-method-settings-candrawoverlays-returns-false-when-user-has

As this is android bug, so I didn't care about this... but I'll try to deal with this anyway.

**Comment by antest1** [comment]
It seems that there are no better way, I just used the delay method. (e18538f)
