### ISSUE TITLE
Akashi Option Loading Error in FleetView in 2.6.0 rev 1

### ISSUE THREAD

**Issue by mindwarp42** [antest1/kcanotify#50]
When tapping on Akashi in FleetView in KCANotify 2.6.0 rev 1, instead of the expected current day's list of possible Akashi improvements,  nothing but the Akashi view title bar is shown.  An error message toast "Error Loading Akashi Data" briefly appears.  If you tap on the Akashi view title bar, a crash report is generated - I unintentionally did that while typing this up on my Samsung Galaxy Tab A 10.1 (2016) tablet and duplicating the actual error on my Moto G5 Plus, both running Android 7.0.  A report from each device has been emailed in.  I did make sure to redownload the resources before running the updated version, and even tried doing so with Kancolle running.  If you go to KCANotify itself, and go to the Improvement Arsenal Chart, that does have the correct information, as verified by crosschecking with akashi-list.me.

**Comment by antest1** [comment]
fixed in 75118d1.

**Comment by mindwarp42** [comment]
I'm laughing solely because you can tell I'm someone who has officially done tech support (and somewhat still officially does) because old habits die hard when it comes to bug filing!  Glad it's technically already fixed by the time I filed, and I'll wait on the next release, since I know the workaround (and at least filing this posts that for others).

**Comment by antest1** [comment]
This problem is fixed in kcanotify 2.6.0 rev2.
I'll close this issue after one week.
