### ISSUE TITLE
private_policy.md OpenDB 주소 변경

### ISSUE THREAD

**Issue by WolfgangKurz** [antest1/kcanotify#51]
도메인 변경 필요합니다.

리디렉션 걸어두긴 했지만 바로 접속할 수 있도록 하는게 여러모로 좋으니까요.

http://opendb.swaytwig.com/

**Comment by antest1** [comment]
네, 해당 부분에 대해서는 변경하도록 하겠습니다. (VPN 관련 내용도 수정해야 하네요)
