### ISSUE TITLE
フィルターの要望

### ISSUE THREAD

**Issue by Nishisonic** [antest1/kcanotify#52]
* 使用しているスマートフォン：Huawei nova lite 2
* Androidのバージョン：8.0
<br>

* フィルターへの追加要望
  * 遠征中の艦と入渠している艦のフィルタ項目が欲しい
* フィルター追加画面の仕様について
  * フィルターの追加画面内で画面の向きを変更(縦↔横)すると、フィルタ項目が全てリセットされてしまうので、そうならないようにして欲しい
  * この動きはソート追加画面内でも発生する

**Comment by antest1** [comment]
画面の仕様については次のアップデートで修正される予定です。
フィルターの追加は時間があれば作業するようにします。

**Comment by Nishisonic** [comment]
Thanks.

**Comment by antest1** [comment]
Added in 2.6.1. 
Close this issue.
