### ISSUE TITLE
Nav Bar/Widget not showing expedition timings.  

### ISSUE THREAD

**Issue by boreslayer** [antest1/kcanotify#54]
Your latest version broke expedition timings.   All timings are not shown on the nav bar and widgets.  
  
Android Ver. 8.1.0

**Comment by XxJimmy122xX** [comment]
Try to restart Kcanotify. Or maybe even reboot your drive. And see if the problem are still there. It worked perfectly fine on my drives. So let's see if this can fix it.

**Comment by boreslayer** [comment]
Rebooting of the drive fixed it.  Thanks!
