### ISSUE TITLE
Question/request sniffer intent

### ISSUE THREAD

**Issue by NoxArt** [antest1/kcanotify#55]
Hi, are there exposed intents to handle enabling/disabling sniffer?

I wanted to use Adblock VPN as well, so the idea was to use Tasker to disable Adblock when switching to DMM or KanColle (https://kb.adguard.com/en/android/solving-problems/tasker) which works, but Kcanotify's sniffer doesn't start if it's disabled - it needs to be enabled. Is there something like the linked page describes (not sure if it would need the security stuff) available and if not, can it be added/exposed?

Thank you for consideration!

**Comment by antest1** [comment]
I haven't used that application, but I think specific receiver is needed to do this stuff.
I'll try to add this one in the following updates.

Please understand that this update can be delayed since I'm too busy nowadays ;)

**Comment by antest1** [comment]
This feature will be added in 2.6.4 version.
You can turn on or off the sniffer by sending intent to Kcanotify.

Package name: ``com.antest1.kcanotify``
Class: ``com.antest1.kcanotify.KcaAutomationReceiver``

| Action | Description |
| --- | ---  |
| ``sniffer_on`` | turn on kcanotify sniffer |
| ``sniffer_off`` | turn off kcanotify sniffer |

Example Screenshot for Tasker: [\[link\]](https://upload.cc/i1/2018/10/08/r6E13C.jpg)

**Comment by NoxArt** [comment]
Works great, thank you, good job!
