### ISSUE TITLE
Sorting/filtering suggestions

### ISSUE THREAD

**Issue by NoxArt** [antest1/kcanotify#56]
Hi, I'd like to suggest:

- sort by 'Name' (e.g. "Haruna")
- maybe filter by 'Name' (partial/contains search)
- filter by 'Can carry daihatsu'

Thank you for consideration!

**Comment by antest1** [comment]
I'll consider about that. Thanks for suggestion.

**Comment by XxJimmy122xX** [comment]
Functions added in 2.7 (95ca653 e81c1a6 247d1ef)

**Comment by NoxArt** [comment]
Amazing, thank you very much!
