### ISSUE TITLE
Improvement arsenal screen suggestions

### ISSUE THREAD

**Issue by NoxArt** [antest1/kcanotify#57]
Hi, some suggestions for Improvement arsenal screen to support being able to decide what to improve

- show (probably both in the list and in details) number of screws
- in details view show how many and how upgraded this equip we already have (the same thing what shows when we click an equip in List of equipment screen ... to avoid constant switching back and forth between these screens)
- show how many of the consumed equipment we have (e.g. for 12.7 Dkai2 Naganami gun show how many unimproved 10cmTwinHA and how many 12.7Ckai we have in supply) ... again to avoid the need to keep switching to list of equipment and search for it

Thank you for consideration!

**Comment by antest1** [comment]
I'll consider about that. Thanks for suggestion.
(Please understand that this update can be delayed since I'm too busy nowadays)

**Comment by NoxArt** [comment]
I think all of these are actually done, so I'll close it then...
Thank you very much!
