### ISSUE TITLE
[WANTED] New Icon for Saury Event

### ISSUE THREAD

**Issue by antest1** [antest1/kcanotify#58]
Kcanotify wants new icon for incoming saury event starts in 10/10.
**The selected icon will be used for the application icon and the play store during saury event.**
If you are interested, please participate! 

## Detail Information
- The image should be **512x512 PNG** file.
  - You can submit 192x192 image as optional, if image is not shown well in .
- The image must be related with **kancolle** and **saury event**. There are no other restrictions 
  (like character / equipment / etc).
- You can participate the event by sending me an email **(kcanotify [at] gmail.com)** with your icon. 
- Your own drawings would be best, but combining existing materials is also ok (if there is no copyright issue).
- The selected images can also be used as main screen or as fairy, if it did not used as application icon but seems to be good to use.
- Copyright belongs to the author. (not transferred to the developer)

## Judging criteria
- Does icon is related with kancolle and saury event?
- Does icon is suitable for using in the kcanotify application?
- Does the developer like that icon? ~(important)~

## Due Date
**2018/10/12 23:59 JST** (the date is tentative; please let me know if you want late submission)

## Reward
- The selected image is used in the application during saury event with the credit.

**Comment by antest1** [comment]
Korean link: 
http://gall.dcinside.com/board/view/?id=kancolle&no=7712672

**Comment by XxJimmy122xX** [comment]
Kcanotify正在為將於10/10舉辦的秋刀魚活動招募新的應用圖標
**一經選定將會在秋刀魚活動期間成為本應用及應用商店中的圖示**
若有興趣歡迎參與！
### ||【詳細資料】||

- 影像大小必須為的**512x512的PNG格式**圖片
  - 若果有特殊情況，192x192的影像大小也可接受

- 圖片主題必需要與**艦隊收藏及秋刀魚活動相關**，此外並沒有限制(例如角色,裝備等)
- 自行作畫當然為最佳，但以現有的材料合成也可(請確保沒有版權問題)
- 若果未能被選為應用圖示但表現出色，仍可被選為使用在主螢幕畫或成為妖精
- 版權屬於作者(並不會轉移至開發者)
### ||【評分準則】||
- 圖示是否與艦隊收藏及秋刀魚活動相關?
- 圖示是否適用於Kcanotify？
- 開發者是否喜歡該圖示？~(很重要)~
### ||【遞交日期】||
**2018/10/12 23:59 JST** (此日期為暫定，遲交請通知)
### ||【獎勵】||
- 被選出的圖示將於秋刀魚活動期間被應用使用(會標示出作者名稱)

**Comment by antest1** [comment]
http://gall.dcinside.com/kancolle/7734874
http://gall.dcinside.com/kancolle/7725896
http://gall.dcinside.com/kancolle/7724904
http://gall.dcinside.com/kancolle/7716795
http://gall.dcinside.com/kancolle/7715047
http://gall.dcinside.com/kancolle/7719200

six icons were submitted. close the issue.
