### ISSUE TITLE
a new release mirror for kcanotify

### ISSUE THREAD

**Issue by TrickLin** [antest1/kcanotify#59]
Developers of Kcanotify,

I am writing on behalf of  Kcwikizh (http://zh.kcwiki.moe/). We also run ooi.moe. Thank you for supporting Ooi in your recent updates, which benefited many Chinese players.

We made a mirror for the Github releases of Kcanotify. It is an accelerated source to download Kcanotify for users in mainland China. It is more convenient than Baiduyun for that it is much faster and does not require a client. The address is https://mirrors.kcwiki.org/kcanotify/. It checks for updates every 30 minutes.

It would be great if you could add it to your official list of sources to download. 

Sincerely,
TrickLin

**Comment by antest1** [comment]
I added kcwiki mirror to the README. I'll soon add to the link in the app.
Thanks for the support.

btw, there is wrongly linked mirror (2,6,3,r1) due to my tag mistake..

**Comment by antest1** [comment]
seems that server is down, is there any issue about the mirror?

**Comment by kozora** [comment]
> seems that server is down, is there any issue about the mirror?

Hi, sorry for it.
I'm the mirror server manager, yesterday the police take down all of the servers in the data center, right now, the server is back up, I will make sure there have another backup server will working when meeting these problems like yesterday.

**Comment by antest1** [comment]
Close this issue as kcwiki mirror has been added to the  in-app APK download site.
