### ISSUE TITLE
Locale(String language, String country) instead of Locale(String language)

### ISSUE THREAD

**Issue by wafer-li** [antest1/kcanotify#6]
I'd like to provide the Simplified Chinese translation.

But, there are also lots of HK and TW players need Traditional Chinese.

I notice that you change the `Locale` by just using the `Locale(String language)` constructor.

It cannot distinguish the simplified and traditional Chinese.

Maybe a new util method is needed to determine the correct constructor.

As this case, it should use the  `Locale(String language, String country)` constructor.

~~Using the `Locale.forLanguageTag(String languageTag)` might be better.~~

**Comment by wafer-li** [comment]
Here are my experiment and results:

![image](https://cloud.githubusercontent.com/assets/12459199/23884044/bfb53f0c-08ad-11e7-9341-314a2b43df01.png)

![image](https://cloud.githubusercontent.com/assets/12459199/23884058/cd970448-08ad-11e7-8135-89fb93592e09.png)

**Comment by antest1** [comment]
Okay, I'll check about it.

**Comment by antest1** [comment]
'Locale.forLanguageTag' requires above API 21 (Lollipop), so it is hard to use since the minimum API is 16 (Jellybean).

Using constructor 'Locale(String language, String country)' seem to be sufficient to distinguish each Chinese, so I'll change all constructors and locale preference to keep locale information like zh-CN/zh-TW.

**Comment by wafer-li** [comment]
OK.

I will soon provide the Simplified Chinese as `value-zh-rCN`.

For the Traditional Chinese, there is a suggestion from an [article](http://gamehk.blogspot.com/2012/12/android-locale-problem-for-hong-kong.html):

> Except for China, all Chinese based region including Hong Kong, Taiwan and Macao are using Traditional Chinese but not Simplified Chinese. It is inconvenient for Traditional Chinese users to read Simplified Chinese. Hence, if your apps would like to provide both Traditional Chinese and Simplified Chinese, please use below settings:

> res/value-zh <- Traditional Chinese
res/value-zh-rCN <- Simplified Chinese

**Comment by antest1** [comment]
Thanks for your support.

Actually, there is already someone who are translating strings to Simplified Chinese. (sorry for speaking late...) but maybe it would be good for checking both translations.

Thank you for suggestion!

**Comment by wafer-li** [comment]
OK, then I will do nothing.

Actually, I don't use Android to play Kancolle.

It is better to hear that there is already the translation.

**Comment by antest1** [comment]
resolved in f419748 and 6df920e, close this issue.
