### ISSUE TITLE
Unable to Select Nova Server as Update Check Server in 2.6.5 rev 1

### ISSUE THREAD

**Issue by mindwarp42** [antest1/kcanotify#60]
In KCANotify 2.6.5 rev 1, when selecting Nova Server under Select Update Check Server in Settings, the radio button can be selected.  However, when the user is taken back to Settings, Backup Server (deprecated) is shown instead of Nova Server as what was chosen, and tapping that to reselect a server has the radio button set to Backup Server (deprecated) instead of Nova Server.  Changing the server to WolfgangKurz Artworks does stick as expected, but if you then try to change from WolfgangKurz Artworks to Nova Server, Backup Server (deprecated) is shown afterwards.  This happened even after a full reboot on both my Samsung Galaxy Tab A 10.1, running Android 7.0, and my Moto G5 Plus, running Android 8.1 (stock on both devices).

**Comment by antest1** [comment]
I'll check about this issue. Thanks for the report!

**Comment by antest1** [comment]
Fixed in 6971c2d.
