### ISSUE TITLE
KCANotify 2.6.5 rev 1 Crashes When Clicking on Airbase Button in FleetView After Kancolle Nov. 16 2018 Update

### ISSUE THREAD

**Issue by mindwarp42** [antest1/kcanotify#61]
When clicking on the Airbase button in FleetView in KCANotify 2.6.5 rev 1, after Kancolle was updated on November 16th, 2018, KCANotify crashes and brings up the option to send in a crash report (mine are sent on both devices).  The Kancolle update did make some changes to the LBAS UI, adding in showing the base range plus how much any recons are adding to that, so that's probably why.

**Comment by antest1** [comment]
will be updated in the next update. (currently all viewers would have this issue)
thanks for the report.

**Comment by antest1** [comment]
Fixed in c1021fd.
