### ISSUE TITLE
After latest update (2.6.6 rev6) App no longer works properly.

### ISSUE THREAD

**Issue by Kranesh** [antest1/kcanotify#64]
So after today's android update, my app doesn't work properly anymore, it doesn't show me information on my fleet, my quests and it also says to open the game via Kcanotify despite already doing that, the only thing that works are the expedition timers and notifications, it also crashes randomly every now and then.

I'm playing from a Motorola Moto G6 plus updated to Android 9.0, the previous version of the app worked like a charm without issues.

**Comment by antest1** [comment]
If you are using android 9.0, there exist a issue that cause sniffer crash. (maybe due to android policy change?) I'll work on it as possible, while since I am in travel...

You may uninstall and re-install 2.6.6 rev4 if you have to use kcanotify right now. Sorry for the inconvenience orz

**Comment by Kranesh** [comment]
Thanks, installing  2.6.6 rev4 fixed the issue for now, hope you guys managed to fix the latest update soon, keep up the good work!

**Comment by antest1** [comment]
Fixed in af9dd0e. (check 2.6.7 update)
If the problem still happens, re-open the issue.
