### ISSUE TITLE
Fairy not appearing on my friend's Galaxy Tab A, and impossible to heartlock ships

### ISSUE THREAD

**Issue by Oradimi** [antest1/kcanotify#65]
As the title says, my friend has a Galaxy Tab A, but the kcanotify fairy doesn't appear in-game. He has another issue but related to the Kancolle client itselfs, he can't heartlock ships because when he tries to drag his cursor on the ship list, the heart icon just doesn't appear.
Can these issues be solved by any way ? Or is it some unknown glitch related to this tablet ?
Thanks in advance !

**Comment by XxJimmy122xX** [comment]
Tell your friend to check if he have give the permission for Kcanotify to display on top of other apps. With the permission allowed, the fairy will pop out. The setting page of Kcanotify can lead you to do it.
For the heartlock problem. I am not sure if he is using the Android version or not. But here is a picture to show him how and where to click.
https://pm1.narvii.com/6513/00e21e08568e498482192e8b02089fe2e2071695_hq.jpg

If he is trying to use HTML 5 Kancolle on phone, then I simply suggest him to heartlock ships with the Android Version or with a proper computer.

**Comment by Oradimi** [comment]
Thanks ! I'll see with him tomorrow.
About the heart issue, he doesn't have any PC, so he can only play on Android. He's using the official Android app. I already told him to try to click directly on the spot where the heart is, but it just selects the ship instead of locking it.

**Comment by antest1** [comment]
About heartlock issue, it is not related with Kcanotify (as it does not affect the kancolle android app directly). Maybe it is due to the device hardware, One possible thing to do is just rotate the screen (after allowing screen rotation) and try to lock the ship, or just reboot the device (as it can be temporal problem).

**Comment by XxJimmy122xX** [comment]
Closed for no further reports and information. Reopen issue if needed.
