### ISSUE TITLE
Shipname misplacement in the dock info

### ISSUE THREAD

**Issue by codedango** [antest1/kcanotify#67]
I cannot describe it exactly.
It just like the screenshot.
And aslo in the construct info.

And when ship is heavily damaged, it shows the alert but without vibrate.
But it vibrates when a expedition is over.

My phone is Xperia ZX1, Android version is Pie, and was not the problem when Android 8.0.

![screenshot_20190219-092320](https://user-images.githubusercontent.com/19159166/52982202-22e0ba00-3428-11e9-90d3-3a4a8878e5f7.png)

**Comment by antest1** [comment]
I'll check about the bug in dock info popup. Thanks for the report!
Maybe the touch vibration is disabled in your phone: this is the new feature in Android P.
check this settings for your device: `Settings -> Accessibility -> Vibration -> Touch vibration` (you have to turn on this)

**Comment by codedango** [comment]
> I'll check about the bug in dock info popup. Thanks for the report!
> Maybe the touch vibration is disabled in your phone: this is the new feature in Android P.
> check below settings for your device:
> Settings -> Accessibility -> Vibration -> Touch vibration (you have to turn on this)
> https://mobilesyrup.com/2018/07/06/android-p-disable-vibrate-notifications/

I turned the touch-vibration on, then the heavily damaged vibration came back.
Thank you very much.

**Comment by codedango** [comment]
Sorry, I should upload the construct info screenshot too.
The duck info popup is fixed, and the construct info is still the same.

![screenshot_20190225-100603](https://user-images.githubusercontent.com/19159166/53309207-ee6a7380-38e9-11e9-9309-c2ddd7013261.png)

**Comment by antest1** [comment]
Okay I'll fix it in the next update TT

**Comment by antest1** [comment]
Fixed in 2.6.7 rev4.
