### ISSUE TITLE
[Feature Request] Add F33/Cn=2 to eLoS Check Options

### ISSUE THREAD

**Issue by mindwarp42** [antest1/kcanotify#68]
Since Phase 2, some maps are using a different variable when performing eLoS checks.  Instead of the standard Cn=1, 3, or 4, a few maps are using Cn=2.  5-2 sticks out, since that's sortied to for a weekly.  Could this option be added to the list of eLoS checks that players can look at?

**Comment by antest1** [comment]
added in 2.6.7 rev3 (acbe3eb).
close the issue.
