### ISSUE TITLE
Provide a document for how to use kcanotify in GotoBrowser

### ISSUE THREAD

**Issue by Angerxu** [antest1/kcanotify#73]
Firstly thanks to your praiseworthy contribution to develope and update.
In newly release 2.6.7 r6, the support of GotoBrowser is added.But i am quite confused of how to set and start in my kcanotify to run GotoBrowser correcly.Meanwhile, it seems that kcanotify can't receive packet normally, because i see nothing in kcanotify when i log in kan-colle game using ooi.moe(by the way i'm a chinese player.)Hope that you can provide a detailed manual for how to use this new browser.Thank u very much.

**Comment by XxJimmy122xX** [comment]
[設定] > [Sniffer設定] > [於其他應用程式中使用Sniffer]
按下於其他應用程式中使用Sniffer，加入GotoBrowser
若果要使用OOI代理，開啟下面那個進階IP

[設定] > [Kcanotify設定] > [選擇要運行的應用程序]
選擇以GotoBrowser開啟

使用說明的話應該正在製作中

**Comment by Angerxu** [comment]
非常感谢，但是我在之前已经尝试以上操作之后，进入游戏界面kcanotify界面依然提示“请在kcanotify界面打开游戏”，显然是没有收到来自游戏的包。@XxJimmy122xX 请问操作您操作成功了吗

**Comment by XxJimmy122xX** [comment]
我是可以正常使用沒錯
Service和Sniffer都打開但仍然[顯示請在介面打開遊戲]的情況下，可以試一下按[戰績表示]然後返回母港，先看看這樣能不能解決。

**Comment by Angerxu** [comment]
@XxJimmy122xX 这似乎不能根本地解决问题？因为kcanotify的工作机制不是应该在游戏启动的时候进行抓包截取api才能正常运作吗？另外经过尝试依然无效，需要提供error log吗？感谢您的解答和帮助

**Comment by Angerxu** [comment]
by the way, the problem still exists under gotobrowser + ooi.moe.I'm sure that i've activate the extended filter and "use for other application" for gotobrowser.

**Comment by antest1** [comment]
Does the problem still exist when you reboot the device?

**Comment by Zexin** [comment]
I have the same problem on both my phone and tablet. I tried reboot but did not work.

**Comment by Zexin** [comment]
I found that cn.kcwiki.org changed its IP to 120.194.85.200. Is it the reason why extended filter does not work well?

**Comment by antest1** [comment]
yes, IP changes cause extended filter not work in kcanotify (as kcanotify checks the network packet based on IP)
I'll update the address in the next update which will released after event starts.

**Comment by Zexin** [comment]
ooi.moe gives a link to the cn.kcwiki.org called 国内高速节点(远端缓存), so we can choose one of the server to run the game. 
And... ooi.moe uses a CDN. The functions worked very well on my Singapore friend's phone.
So maybe ooi.moe gives different IPs to people in China mainland and others?

**Comment by Angerxu** [comment]
@antest1 Firstly thanks to work in v2.7.Sadly, this problem seems still exists.In other word, kcanotify does'nt have any output after stating game in gotobrowser.By the way, the function of subtitle works normally in gotobrowser.

**Comment by Zexin** [comment]
@antest1 Thank you for your work very much. Sorry I forgot gotobrowser can not fit kcwiki . But I can see data from kcwiki in kcanotify now.
Can you allow us add IP by ourselves?
I think it is an easier way to solve the cdn problem.

**Comment by XxJimmy122xX** [comment]
Github Wiki added.
Information of what this issues asking for [here](https://github.com/antest1/kcanotify/wiki/GotoBrowser).
