### ISSUE TITLE
To update Pop-up fleet view early

### ISSUE THREAD

**Issue by NoxArt** [antest1/kcanotify#74]
Whenever a combat ends, if you click a fairy to open FleetView, it shows data from before the battle started
However when any is taiha'd during the battle, the fairy is red already at that point, so I assume KCA does have data from the battle available.
Can the FleetView be updated at that point?
Thank you for consideration

**Comment by antest1** [comment]
Sorry for late check.

I'll consider about that. Maybe the time after battle ends and the map appears?

**Comment by antest1** [comment]
updated in 3cf5f83.

**Comment by NoxArt** [comment]
Sorry for being late too, thank you very much!
