### ISSUE TITLE
Issues with sniffer (Both Passive and Active)

### ISSUE THREAD

**Issue by takase1121** [antest1/kcanotify#77]
When I use active sniffer, kancolle (gotobrowser) frequently drop its connection. kept getting error cat screen with bunch of axios errors.
I tried passive sniffer but it doesn't work. no overlay shown

**Comment by antest1** [comment]
When using passive sniffer, you must set "Broadcast Mode" when starting game with GotoBrowser.
About active sniffer, is there any battery saver app or are you using the other VPN app?

**Comment by takase1121** [comment]
I see. The battery saver sure reminds me of MIUI battery saver (this is not the first time MIUI bloatware feature caused me issues). Anyways I'll see if Active Sniffer works with those disabled. Now I finally know how to use passive sniffer and those issues are mostly gone magically and I don't have annoying VPN notification. Thanks a lot!
