### ISSUE TITLE
Game Data(api_start2) can't be updated

### ISSUE THREAD

**Issue by XxJimmy122xX** [antest1/kcanotify#78]
Due to some server problems. Game Data(api_start2) can't be upgraded from 4.5.1.3 to 4.5.1.4
Although this won't cause critical problems on the functions. But the unupgraded game data with cause CL Perth HP couldn't be shown correctly.  So here to notice users to beware of that.

Issues will close down when problem is fixed.
21:48   18/12/2019

**Comment by mikexyx** [comment]
And now(few days ago) I can't upload 4.5.1.5 either

**Comment by ivon852** [comment]
Same here. I cannot update from 4.4.8.0 to newest 4.5.1.9. It always shows "not valid data"

**Comment by antest1** [comment]
Fixed the issue. (it was caused by server fault: there was no storage left)
