### ISSUE TITLE
Kcanotify not responding

### ISSUE THREAD

**Issue by takaizu91** [antest1/kcanotify#79]
Hi,

I'm having an issue which I can't use kcanotify fleet / battle view since the fairy didn't respond to any action except moving the fairy icon. Can't be certain sniffer also took a hit because I can't check my data through fleet view but I can still access to kancolle with sniffer on

Error log attached together
[Error log](https://drive.google.com/file/d/1FzbVYg0xU4FUnuKj6xnDUEObiC2NLHim/view?usp=drivesdk)

**Comment by antest1** [comment]
Try to reset the game data and resources, and try to download the game data again?

**Comment by takaizu91** [comment]
I had reset the game data and resources. I think i have found the problem. Fleetview works when regular shipgirls were set to secretary but when 'Shinshuu Maru' were set to secretary, it immediately bugged and fleetview no longer work until I set to another secretary before reset the game

**Comment by antest1** [comment]
It seems that the new game data has not been loaded normally. In this case, just completely restarting the kcanotify will solve the problem (the easiest way is just reboot the device)

**Comment by takaizu91** [comment]
I turn off the service before re-download the game data again to be sure, fleetview now works with the new shipgirls. Thanks for the assist.
