### ISSUE TITLE
Get locale code from string.xml instead of Locale

### ISSUE THREAD

**Issue by wafer-li** [antest1/kcanotify#8]
There is some problems in the current i18n implementation.

Let me explain it:

### Background
There is lots of regions in the Chinese language zone, such as CN, HK, TW, MO and SG.

But there are only two main language variants: the Simplified Chinese(简体中文) and the Traditional Chinese(繁體中文).

The CN and SG use Simplified Chinese, and the rest of the regions use Traditional Chinese.

We should use Traditional Chinese as the **fallback**, because it covers more regions.

As above, we came across the project struct, as I mentioned at https://github.com/antest1/kcanotify/issues/6#issuecomment-286493663:

```
value-zh => Traditional Chinese
value-zh-rCN => Simplified Chinese
value-zh-rSG => Simplified Chinese
``` 

### Problem

There comes the problem, we only have two language variants, and need to deal with a lot of regions.

Now the project using the following [code](https://github.com/antest1/kcanotify/blob/c3028727109c90233f396a87919c739196958eff/app/src/main/java/com/antest1/kcanotify/MainActivity.java#L297) to retrieve the localecode:

```java
String language = Locale.getDefault().getLanguage();
String country = Locale.getDefault().getCountry();
```

And the `languageOptionValue` only provide two `zh` value: `zh-CN` and `zh-TW`

What if a user in HK, and the default locale is `zh-HK`, as the structure above, it will fallback to `value-zh` which provides the Traditional Chinese.

But, there is no `zh-HK` in `languageOptionValue`, then the entry of Language Setting will display the **English**.

And when the user restart the app, it will set the Configuration Locale to English even if we have the correct Localized Resource.

### Solution

As [This StackOverflow](http://stackoverflow.com/questions/8690460/how-to-get-language-locale-currently-android-app-displays) describe, we should set the correct `localecode` in each `strings.xml`.

And retrieve the `localecode` in `strings.xml` which is the **real** currently using language variant.

**Comment by antest1** [comment]
Since the locale of application is set in [`KcaApplication.java`](https://github.com/antest1/kcanotify/blob/c3028727109c90233f396a87919c739196958eff/app/src/main/java/com/antest1/kcanotify/KcaApplication.java with preference, so it won't set the locale to English after restart.

But your solution seems to be more clear, I'll merge your commit after checking any dependencies for `getLocaleInArray`.

**Comment by wafer-li** [comment]
> But your solution seems to be more clear, I'll merge your commit after checking any dependencies for getLocaleInArray.

The `getLocaleInArray()` only used in [`MainActivity#setDefaultPreference()`](https://github.com/antest1/kcanotify/blob/c3028727109c90233f396a87919c739196958eff/app/src/main/java/com/antest1/kcanotify/MainActivity.java#L300).

That is why I delete that method.

======

>Since the locale of application is set in KcaApplication.java with preference, so it won't set the locale to English after restart.

Actually, it will.

As the app first boot, the locale of configuration is the default, let's say, `zh-HK`.

And the Preference is set at `MainActivity#setDefaultPreference()`.

As there is no `zh-HK` locale code,  it will **fallback to `en-US`**.

> You use `zh-TW` to represent Traditional Chinese at [`getLocaleCode()`](https://github.com/antest1/kcanotify/blob/c3028727109c90233f396a87919c739196958eff/app/src/main/java/com/antest1/kcanotify/LocaleUtils.java#L40)

Now the Language Preference is `en-US`, which is English.

And when the app restart, **without** changing any Preference, which means the Language Preference is **still** English.

Therefore, it will use the `en-US` locale, which will cause the Language to be English.

**Comment by antest1** [comment]
Oh, I now understand. I didn't notice that problem. It should be fixed.
Thanks for kind explanation!
