### ISSUE TITLE
Fleet View won't show up once I get to the homeport

### ISSUE THREAD

**Issue by semperfi201** [antest1/kcanotify#80]
Once I get to homeport clicking the fairy won't show fleetview at all. 
`[F]	2.8r6	fleetview	java.lang.ClassCastException: com.google.gson.JsonNull cannot be cast to com.google.gson.JsonObject / at com.google.gson.JsonObject.getAsJsonObject(JsonObject.java:1) / at com.antest1.kcanotify.KcaFleetViewService.processDeckInfo(KcaFleetViewService.java:120) / at com.antest1.kcanotify.KcaFleetViewService.setView(KcaFleetViewService.java:6) / at com.antest1.kcanotify.KcaFleetViewService.onStartCommand(KcaFleetViewService.java:4) / at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4298) / at android.app.ActivityThread.access$2700(ActivityThread.java:273) / at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2070) / at android.os.Handler.dispatchMessage(Handler.java:112) / at android.os.Looper.loop(Looper.java:216) / at android.app.ActivityThread.main(ActivityThread.java:7625) / at java.lang.reflect.Method.invoke(Native Method) / at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524) / at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987) / 	FV_0	[{"api_member_id":20543437,"api_id":1,"api_name":"main","api_name_id":"","api_mission":[0,0,0,0],"api_flagship":"0","api_ship":[102681,105810,105811,-1,-1,-1]},{"api_member_id":20543437,"api_id":2,"api_name":"main","api_name_id":"","api_mission":[1,2,1577731904036,0],"api_flagship":"0","api_ship":[13678,15,9758,90821,-1,-1]},{"api_member_id":20543437,"api_id":3,"api_name":"node supp","api_name_id":"","api_mission":[1,5,1577736244975,0],"api_flagship":"0","api_ship":[38098,7369,29099,28980,20989,-1]},{"api_member_id":20543437,"api_id":4,"api_name":"boss supp","api_name_id":"","api_mission":[1,38,1577734712997,0],"api_flagship":"0","api_ship":[13610,26,8992,9,61357,41740]}]	2019-12-30 19:41:34`
That's what the error log shows. Reinstalling also doesn't work.

**Comment by semperfi201** [comment]
I tried rolling back to 2.8 rev5 version again, and I can open Fleet View after getting to homeport just fine. Looks like the problem only occurs in 2.8 rev6

**Comment by antest1** [comment]
Does the problem still exist for the latest version?

**Comment by semperfi201** [comment]
The problem doesn't exist anymore since 2.8 rev8, and of course in latest version too.

**Comment by antest1** [comment]
ok, then I'll close this issue.
