### ISSUE TITLE
Screen Overlay Issue....

### ISSUE THREAD

**Issue by NekoAlycia** [antest1/kcanotify#82]
Yes, it's quite simple but I'm using Lenovo Tablet TB-7504X. I can't find this setting. Is there any other way to give access to Kcanotify so I can see my fairy...?

**Comment by XxJimmy122xX** [comment]
It's Android anyway. Try pressing "Screen Overlay Settings" at the Permission/Function Settings tab. It should lead you to the setting page of your system to let you allow the permission for the app.

**Comment by XxJimmy122xX** [comment]
Reopen if anyone have the same question
