### ISSUE TITLE
Update on poi db reporting hostname

### ISSUE THREAD

**Issue by KagamiChan** [antest1/kcanotify#83]
Hi, this is Kagami from poi dev team.

Thanks for reporting data to poi db. We've started using the new hostname for poi db: `api.poi.moe`, and the legacy one `poi.0u0.moe` is going to be deprecated sometime. Could you please help update the hostname in Kcanotify, looks like it is this line:

https://github.com/antest1/kcanotify/blob/817f5a830e15054d4637e756c0174c8258909239/app/src/main/java/com/antest1/kcanotify/KcaPoiDBAPI.java#L130

**Comment by antest1** [comment]
checked

**Comment by antest1** [comment]
updated
