### ISSUE TITLE
On Poi DB update

### ISSUE THREAD

**Issue by KagamiChan** [antest1/kcanotify#84]
Hi, recently we rethink about poi db design and make something new in the server. Could you please help make the update on the reporting part?

These new things are:
1. the server is using https now, and the server name is `https://api.poi.moe`
2. we now support pure json payload and it is recommended to use
3. A new header `X-Reporter` is supported for reporting the reprter id so that some reporters having difficulties specifying user agent (namely those running in browsers) could properly identify themselves. This is not mandatory for kcanotify though.

Please let me know if you need any help, or I can draft a PR later if needed

**Comment by antest1** [comment]
I'll work on this issue soon. Thanks for sharing the information 👍

**Comment by antest1** [comment]
updated in kcanotify 2.8.2 rev1

**Comment by KagamiChan** [comment]
Thank you very much!
