### ISSUE TITLE
Change to hash to avoid HTTP 414

### ISSUE THREAD

**Issue by HitomaruKonpaku** [antest1/kcanotify#85]
Hi,

Can you please update the export to KCImgBuilder following this issue https://github.com/KC3Kai/KC3Kai/pull/3107

https://github.com/antest1/kcanotify/commit/a905f76b8e796c7c62a5c82a5196fd04d4f44310#diff-3307eafd144ad350fa15fabd6815a3e4ab13c02c9747471f90c2c963a1139cb0R194

**Comment by antest1** [comment]
I checked this issue late ;-;
will be updated on the next release (2.8.2 rev5) on next week.
