### ISSUE TITLE
FleetView enhancements about Akashi's repair

### ISSUE THREAD

**Issue by rassvet2** [antest1/kcanotify#88]
I want to find out when and how much progress will be made on Akashi's Anchorage Repairs, so I'm writing Pull Request.
I will put it on the right of HP, like `"71/78 +4(17:20)"`.
the `"4"` means that going to the home screen will recover 4 HP.
the `"17:20"`(countdown) means that after 17m 20s will recover 1 more HP.

I'm going to use the formula from `KcaDocking#getDockingTime`, "https://wikiwiki.jp/kancolle/%E6%98%8E%E7%9F%B3#hakuchi" and "https://wikiwiki.jp/kancolle/%E5%85%A5%E6%B8%A0#i43fa2e3".

On a related note, I'm going to do a major rewrite of `KcaFleetViewService#processDeckInfo`.

how about this?
<img width="500" alt="draft" src="https://user-images.githubusercontent.com/50271984/142754493-47e431b9-1b46-443b-8986-238a16aef2c5.png">

If necessary, I will say it again in Japanese. It's more accurate.

**Comment by laplamgor** [comment]
I think you can directly submit a PR for @antest1 to review :)

**Comment by rassvet2** [comment]
I did it. Thanks!
