### ISSUE TITLE
The equipment count (in FleetView) was (a bit) broken by the update of 01/21.

### ISSUE THREAD

**Issue by rassvet2** [antest1/kcanotify#92]
The Damage Control and the Combat Rations(応急修理要員/応急修理女神/戦闘糧食) were excluded from the equipment count(in game) by Jan 21 update, but are still included in the user-item list (such as used in `KcaDBHelper#getItemCountByKcId`).
It seems that the number of excluded equipment is just subtracted from the total.
In my case, `equip count + dmgcon + ration` exactly matches to the equipment count in FleetView.

the update tweet: [08▼【装備運用枠】の更新実装 1/2](https://twitter.com/KanColle_STAFF/status/1484487043409317891), [08▼【装備運用枠】の更新実装 2/2](https://twitter.com/KanColle_STAFF/status/1484487083863404544)

**Comment by laplamgor** [comment]
Will you be able to work on an update / PR alone?
I'm still a bit busy until mid Feb and not sure about A.N. Thanks

**Comment by rassvet2** [comment]
Finished, easy as pie.

**Comment by antest1** [comment]
sorry, I already worked on this issue before your PR orz
but thanks for the contribution!
