### ISSUE TITLE
Request for confirmation of acceptance of exercise mission

### ISSUE THREAD

**Issue by KimidoriBoushi3** [antest1/kcanotify#97]
Request.
I am using a translation site, sorry for any rudeness.

Can you implement a feature that notifies the user when the exercise screen is opened, if the exercise mission has not been accepted?

It would be similar to the notification for an expedition that has not yet been resupplied.

If possible, please consider.

**Comment by antest1** [comment]
hello, we are not adding features for kcanotify now except for critical issue. (as I'm not playing kancolle orz)
but thanks for the suggestion!
