### ISSUE TITLE
資料轉移問題

### ISSUE THREAD

**Issue by siyouyu** [antest1/kcanotify#99]
目前準備更換新手機
請問舊手機的資料要怎麼轉移到新手機裡面?

**Comment by skysumbra** [comment]
![Screenshot_2023-08-24-08-54-56-16_754d24f0d81f64982887e4b87363a532](https://github.com/antest1/kcanotify/assets/24444616/24803b18-d5af-4907-8bed-075d0636e358)

你試試設定內備份，然後將備份拿出，之後在放回指定的路徑
